### ISSUE TITLE
How to record?

### ISSUE THREAD

**Issue by ArchGalileu** [fwestenberg/reolink#10]
Hello how to record?

Best regards
ArchGalileu

**Comment by emericklaw** [comment]
I have not tried it myself since I use an external DVR but the documentation here under ‘Service record’ may work?

https://www.home-assistant.io/integrations/camera/

**Comment by fwestenberg** [comment]
When I login to the webview of the camera, I do not see a recording option.

![image](https://user-images.githubusercontent.com/47930023/69780177-c4ace880-11aa-11ea-8947-38efa94a7d6e.png)

@ArchGalileu What exacly would you like to have? I think a little more info would help.

**Comment by IsaTTeN** [comment]
Hello,

Thanks for this nice custom component!!!

I´ve tried to use the camera.record or camera.snapshot with your custom component but it doesn´t work. I get this error:

`2020-01-01 22:33:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140656349256592] a bytes-like object is required, not 'HTTPResponse'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 360, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 659, in async_handle_snapshot_service
    await hass.async_add_executor_job(_write_image, snapshot_file, image)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 656, in _write_image
    img_file.write(image_data)
TypeError: a bytes-like object is required, not 'HTTPResponse'`

If I configure the reolink camera like a generic camera I can use the caemra.record and camera.snapshot

**Comment by fwestenberg** [comment]
I just created a new pull request. Snapshot is fixed now!

**Comment by IsaTTeN** [comment]
How fast!!!

I just downloaded it! I will test it very soon and say how it works!!

Thanks a lot

**Comment by IsaTTeN** [comment]
It works like a charm!!!!

**Comment by IsaTTeN** [comment]
The camera.record service is still not working. I supose it requires more work. I get this error:

"Call-service API error. Error Message: camera.rampa does not support record service"

**Comment by fwestenberg** [comment]
The record service is indeed not implemented. I will work on this a.s.a.p.

**Comment by IsaTTeN** [comment]
No hurry!

**Comment by fwestenberg** [comment]
If you have an NVR recorder, there will probably be an record option? @begicj do you know if this exists and what's the URL? 
For people like me, who only have a cam without NVR there simply is no recording functionality provided by the cam for as far as I know.

**Comment by begicj** [comment]
Yes there is option for recording, see picture below.

This is link: 

http: //IP_of_NVR/cgi-bin/api.cgi? cmd=SetRec&token=someletters&user=user&password=mypass with POST method and body 

[{"cmd":"SetRec","action":0,"param":{"Rec":{"channel":1,"overwrite":1,"packTime":"60 Minutes","postRec":"2 Minutes","preRec":1,"schedule":{"enable":1,"table":"222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222"}}}}]

And response is:

[
   {
      "cmd" : "SetRec",
      "code" : 0,
      "value" : {
         "rspCode" : 200
      }
   }
]

![60C53A57-A4EE-4D05-B20D-D169DDC3B525](https://user-images.githubusercontent.com/24259043/71748554-35fb4d80-2e73-11ea-9ae0-f63133a18492.jpeg)

**Comment by extin** [comment]
This may not be what OP meant, but I can confirm that you can enable/disable recording to camera SD via POST payload:
`[{"cmd":"SetRec","action":0,"param":{"Rec":{"channel":0,"schedule":{"enable":1}}}}]`
or enable = 0 on URL `your-camera-ip/cgi-bin/api.cgi?cmd=setRec&token=sometoken`
This work even if you don't have the enable option visible in the web-ui.
I'd very much like the option to set this via HA, so I you don't get unnecessary recordings when you're home.

**Comment by fwestenberg** [comment]
Please check out the latest release v0.2.
